name: "npm Audit Action"
description: "Runs npm audit and publishes vulnerabilities as warnings"
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "16"
runs:
  using: "node16"
  main: "index.js"
